### ISSUE TITLE
What happens if a config option is tied to an evironment variable AND is defined in the config file?

### ISSUE THREAD

**Issue by yannlandry** [taskcluster/taskcluster-cli#105]
While going over [config/serialization](https://github.com/taskcluster/taskcluster-cli/blob/install-cobra/config/serialization.go#L34) I realized that there might be issues when some options are defined both as environment variables and as config file values.

I assume that when an option is tied to an environment variable, we will need to edit that environment variable to change the value of that option. But what happens if I do `taskcluster config set OPTION VALUE`? Which value then takes precedence?

**Comment by yannlandry** [comment]
@jonasfj I believe you originally wrote that code, did you have anything in mine for such scenario? Otherwise we'll try to define something.

**Comment by jonasfj** [comment]
hmm, that's a good question...

I suspect env vars takes precedence over the config file...
I'm thinking in some cases you might call like this:
`AUTH_BASE_URL='....' taskcluster expand-scopes my-scope`

So precedence would be (in order of preference):
 1) Command line option passed
 2) Value from environment variable
 3) Value from config file
 4) Default value (burned into the binary)

Does that make sense?

**Comment by djmitche** [comment]
@lteigrob fyi, I know you've been looking at this code too.  This precedence might be a good thing to test, since changing it unintentionally could surprise users.

**Comment by djmitche** [comment]
I'd like to eventually get rid of the config-file support.
