### ISSUE TITLE
New feature: Cancel a subset of a group

### ISSUE THREAD

**Issue by JohanLorenzo** [taskcluster/taskcluster-cli#126]
This need came out last Friday, when releng had several releases in flight and all of them were claiming the same workers. One way to solve this issue is to [handle priorities in a different manner](https://bugzilla.mozilla.org/show_bug.cgi?id=1348773). Nonetheless, having a manual way to cancel/rerun a certain type of tasks, would be great to manually help a graph to claim workers.

For example:
```sh
taskcluster group cancel --worker-type 'signing-worker-v1' $TASK_GROUP_ID
```
will:
1. look for unscheduled/pending/running tasks that match this worker type
1. display the name of the tasks found
1. ask for a confirmation
1. if confirmation given, cancel them

`rerun` may also follow the same workflow.

What do you guys think?

**Comment by djmitche** [comment]
I like this!  @yannlandry do you want to jump on this one?

**Comment by yannlandry** [comment]
Yep, time to jump on task management!

**Comment by escapewindow** [comment]
In this workflow, we want `rerun` to only rerun the previously cancelled jobs.

e.g.
- we have task1 and task2, both blocking downstream tasks
- task1 is completed, and downstream tasks have also completed
- task2 is cancelled, and downstream tasks are pending

If we rerun task2, all is as expected: task2 completes for the first time, and downstream tasks are unblocked.

If we rerun task1, completed downstream tasks don't necessarily retrigger, and we may end up with indexes and routes with differing artifacts+hashes than expected.
