### ISSUE TITLE
`taskcluster signin` fails to open browser on OS X

### ISSUE THREAD

**Issue by escapewindow** [taskcluster/taskcluster-cli#159]
I tried the latest darwin build from the readme, plus my locally built version which used to work.
`taskcluster signin` no longer opens a tab to sign in.  I've tried with Nightly and Firefox, with tmux and without.

**Comment by djmitche** [comment]
Does anything happen?

**Comment by escapewindow** [comment]
I get

```
Starting
Listening for a callback on: http://localhost:51042
```

which is normal.  What isn't normal is no tab opens to login.tc.net.

**Comment by djmitche** [comment]
Thanks -- @jonasfj can you double-check this?  It's never worked for me so I'm not a great help :)

**Comment by djmitche** [comment]
@mozbhearsum just reported that it works OK for him, too..

**Comment by mozbhearsum** [comment]
Worked fine for me just now for what it's worth. Latest binary from the README, Ubuntu 16.10, Firefox Beta.

**Comment by escapewindow** [comment]
Still broken for me. I rebuilt from HEAD and that's broken too.
Not finding a -v option to debug.

**Comment by djmitche** [comment]
I'm assuming it's failing to start the browser.  It doesn't ordinarily report such errors (maybe it should?).  @jonasfj can hopefully say more..

**Comment by jonasfj** [comment]
Works for me too...

Okay, so it's the browser opening the fails, I suggest that:
 A) We print the link you're supposed to open (most terminals have a "right click -> open link" menu)
 B) We find out somehow to get browser windows opening on OS X

**Comment by escapewindow** [comment]
This prints the url, plus "Opened the window!" but no window.
If I copy/paste the url into the browser, signin works!
Pretty sure that means the `webbrowser.Open` call broke for me for some reason.

```diff
diff --git a/cmds/signin/signin.go b/cmds/signin/signin.go
index 12c2fa5..95f9201 100644
--- a/cmds/signin/signin.go
+++ b/cmds/signin/signin.go
@@ -118,9 +118,11 @@ func cmdSignin(cmd *cobra.Command, _ []string) error {
        loginURL := config.Configuration["signin"]["loginUrl"].(string)
        loginURL += "/?target=" + url.QueryEscape(target) + "&description=" + description

+        fmt.Fprintln(cmd.OutOrStdout(), "Login url "+loginURL)
        // Open browser
        fmt.Fprintln(cmd.OutOrStdout(), "Listening for a callback on: "+target)
        webbrowser.Open(loginURL, webbrowser.NewWindow, true)
+        fmt.Fprintln(cmd.OutOrStdout(), "Opened the window!")

        // Start serving
        s.Serve(listener)
```

**Comment by escapewindow** [comment]
This gives me

```
Listening for a callback on: http://localhost:51210
Error :exit status 1
&{0xc42000c220} exit status 1
Opened the window!
```

Is there something that can tell me more about that error?  I'm not a go programmer.

```diff
diff --git a/cmds/signin/signin.go b/cmds/signin/signin.go
index 12c2fa5..92f18b1 100644
--- a/cmds/signin/signin.go
+++ b/cmds/signin/signin.go
@@ -118,9 +118,15 @@ func cmdSignin(cmd *cobra.Command, _ []string) error {
        loginURL := config.Configuration["signin"]["loginUrl"].(string)
        loginURL += "/?target=" + url.QueryEscape(target) + "&description=" + description

+        fmt.Fprintln(cmd.OutOrStdout(), "Login url "+loginURL)
        // Open browser
        fmt.Fprintln(cmd.OutOrStdout(), "Listening for a callback on: "+target)
-       webbrowser.Open(loginURL, webbrowser.NewWindow, true)
+       browserErr := webbrowser.Open(loginURL, webbrowser.NewWindow, true)
+        if browserErr != nil {
+                fmt.Fprintln(cmd.OutOrStdout(), "Error :"+browserErr.Error())
+                fmt.Println(cmd.OutOrStdout(), browserErr)
+        }
+        fmt.Fprintln(cmd.OutOrStdout(), "Opened the window!")

        // Start serving
        s.Serve(listener)
```

**Comment by escapewindow** [comment]
Replacing `/src/go/src/github.com/taskcluster/taskcluster-cli/vendor/github.com/bryanl/webbrowser/osx.go` with the following fixes it. I'm not sure what to do for a real fix, but this works for now:

```golang
package webbrowser

import (
//      "fmt"
        "os/exec"
//      "strings"
)

// OSXOpener is an Opener for Mac OSX.
type OSXOpener struct {
        Env []string
}

var _ Opener = &OSXOpener{}

// Open opens a URL using osascript..
func (o *OSXOpener) Open(u string, windowType WindowType, autoRaise bool) error {
//      script := fmt.Sprintf(`open "%s"`, strings.Replace(u, `"`, "%22", -1))
//      fmt.Println(script)
//      cmd := exec.Command("/usr/bin/osascript", "-e", script)
        cmd := exec.Command("open", u)
        return cmd.Run()
}
```

**Comment by escapewindow** [comment]
If other people are seeing this, I suggest we stop using `OSXOpener` or forking the webbrowser project, since I'm seeing no response in https://github.com/bryanl/webbrowser/issues/4 . If no one else is seeing this, I'm happy to keep my local patch.

**Comment by jonasfj** [comment]
@escapewindow, I already moved this to use `github.com/pkg/browser`, does that work for OS X...

(I think bstack tested it for me)

**Comment by escapewindow** [comment]
Nice! The link in the README wfm. Thanks!
