### ISSUE TITLE
Taskcluster signin doesn't have a "Grant Credentials" section on Windows

### ISSUE THREAD

**Issue by rvandermeulen** [taskcluster/taskcluster-cli#161]
I downloaded the Win64 version of taskcluster.exe from https://tools.taskcluster.net/index/artifacts/project.taskcluster.taskcluster-cli/latest and put it in my path. When I run |taskcluster signin|, I get redirected to an Okta login in a new browser tab as expected. After logging in, however, I get a Taskcluster page that only offers the 3 login options at the top and my credentials at the bottom - no "Grant Credentials" section in the middle.

I was able to successfully get a "Grant Credentials" URL from aki and change the port it was listening on and was then able to click the Grant Access button, which then allowed taskcluster to save the credentials.

**Comment by djmitche** [comment]
@jonasfj can you take a peek at this?

**Comment by jonasfj** [comment]
This could be something with how we open urls on windows maybe?
I'm guessing we could additionally print the URL in your shell...

**Comment by jonasfj** [comment]
There is a bug in the webbrowser thing we're using... let's switch to: https://github.com/pkg/browser

Notably, the one we have don't use: https://github.com/pkg/browser/blob/c90ca0c84f15f81c982e32665bffd8d7aac8f097/browser_windows.go#L8

So we can't have `&` the URL...

**Comment by jonasfj** [comment]
Hopefully fixed in: https://github.com/taskcluster/taskcluster-cli/pull/162

**Comment by t0xicCode** [comment]
@rvandermeulen Could you update to v0.8.0 and confirm that it's been fixed?

**Comment by djmitche** [comment]
Note that it's currently got support only for bash and bourne shells.

**Comment by rvandermeulen** [comment]
Yes, printing the URL works fine now.
