### ISSUE TITLE
Update meta-linter config

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-cli#171]
To something like this:
https://github.com/taskcluster/taskcluster-worker/blob/79da11e34f8b2e7ef8a01c101749717e00b1666b/Makefile#L91-L105

**Comment by djmitche** [comment]
@jonasfj does this mean changing which linters we invoke?  Are there specific desirable linters we're not using?

**Comment by jonasfj** [comment]
I can't remember.. I would just run them all like we do in tc-worker.

fyi, no rush, or reason we shouldn't do this next time someone gets around to hack on this...

**Comment by djmitche** [comment]
We no longer use gometalinter.
