### ISSUE TITLE
fix output from browser in `taskcluster signin`

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-cli#177]
After running `stdout` looks like:
```
Created new window in existing browser session.
export TASKCLUSTER_CLIENT_ID='mozilla-ldap/jojensen@mozilla.com/cli'
export TASKCLUSTER_ACCESS_TOKEN=
```
and useful messages to `stderr`... 

Probably we need to hack the library we use to open the browser to redirect it's output to stderr...

**Comment by djmitche** [comment]
Hm, I didn't have that problem.  But yes, that would be a good fix.
