### ISSUE TITLE
Add slugid command

### ISSUE THREAD

**Issue by walac** [taskcluster/taskcluster-cli#18]
A slugid is an [uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier) used to uniquely identify tasks. The goal here is to make [slugid-go](https://github.com/taskcluster/slugid-go) interface into a `taskcluster-cli` command:

``` shell
taskcluster slugid v4
taskcluster slugid nice
taskcluster slugid from-uuid <uuid>
taskcluster slugid to-uuid <slugid>
```

**Comment by ApheleiaS** [comment]
Hello, 
Can you please assign me to this bug? 
Thanks :)

**Comment by walac** [comment]
It is yours, please accept team member invitation to make the assignment.

**Comment by walac** [comment]
Update: sorry, but you are already assigned to bug #20, once you are done there, you can pick this.

**Comment by djmitche** [comment]
@petemoore points out this already exists in the https://github.com/taskcluster/pulse-go project

**Comment by djmitche** [comment]
Although now that I see #24, this makes sense, too:
```
TASKID=$(taskcluster slugid)
cat <<EOF | taskcluster queue createTask $TASKID
...
```

**Comment by petemoore** [comment]
> @petemoore points out this already exists in the https://github.com/taskcluster/pulse-go project

It actually exists here:
https://github.com/taskcluster/slugid-go#command-line-usage

I tend to think we don't need anything here, and we can close this issue.
@djmitche ok with you?

**Comment by djmitche** [comment]
Oops, yes, I copied the wrong URL.

I think this would fit well into the formulation above for creating a new task from a shell script.  Installing a separate binary just to generate a slugid goes against the everything-in-one-package approach for taskcluster-cli.  And this is going to be a very simple plugin!

**Comment by yannlandry** [comment]
On it, replacing `from-uuid` to `encode` and `to-uuid` to `decode`.
