### ISSUE TITLE
Using taskcluster-cli cleanly within multiple shells

### ISSUE THREAD

**Issue by srfraser** [taskcluster/taskcluster-cli#181]
In the current incarnation, we need to copy/paste the two environment variables into each shell we'd like to use `taskcluster` in, since it doesn't store them on disk any more.

A clean way of using the cli in multiple shells would be very helpful. 

I know that the commit message says the client still reads from `taskcluster.yaml`, but since I deleted this file to try and work out some issues, I no longer have a reference copy to put those values in - I don't know the format.

How much of a benefit is there to avoid writing these temporary credentials to disk, given that they're temporary?

**Comment by djmitche** [comment]
One option might be:

```
$ taskcluster signin > /dev/shm/creds && source /dev/shm/creds
```

and then in another shell, just run the `source` part.  You could even work that `source` into your `.bashrc` or equivalent, or maybe build some shell function that looks at the age of /dev/shm/creds and only runs `taskcluster signin` if they are too old, then sources them regardless.

If you come up with something nice, I'd be happy to include it in the docs.

It's OK if you decide to write to disk (noting that /dev/shm is *not* disk, but if that was `~/.tc-signin` that would be OK too).  I just don't want to do that by default.  There's risk of other processes reading the data (even my example above doesn't set file permissions correctly) and of an attacker capturing a powered-on laptop and extracting the secrets that way.  So it's more of a defense-in-depth thing.

**Comment by djmitche** [comment]
@srfraser did #182 solve this?
