### ISSUE TITLE
taskcluster signin not working on Windows

### ISSUE THREAD

**Issue by Archaeopteryx** [taskcluster/taskcluster-cli#185]
On Windows 8.1 with the latest taskcluster cli executable for x64, authentication doesn't allow to run commands:

`taskcluster signin
Starting
Listening for a callback on: http://localhost:50443
Opening URL: https://tools.taskcluster.net/auth/clients/new?name=cli&description=Temporary+client+for+use+on+the+command+line&scope=%2A&expires=1d&callback_url=http%3A%2F%2Flocalhost%3A50443
export TASKCLUSTER_CLIENT_ID='mozilla-ldap/<my ldap id>/cli'
export TASKCLUSTER_ACCESS_TOKEN='looksLikeARealToken'
Credentials output as environment variables

F:\Download\Mozilla\taskcluster-cli
taskcluster task rerun JR-H-z2RT9uz75c96BR_-Q
Error: could not rerun the task JR-H-z2RT9uz75c96BR_-Q: (Permanent) HTTP response code 401
HTTP/1.1 401 Unauthorized
Content-Length: 380
Access-Control-Allow-Headers: X-Requested-With,Content-Type,Authorization,Accept,Origin
Access-Control-Allow-Methods: OPTIONS,GET,HEAD,POST,PUT,DELETE,TRACE,CONNECT
Access-Control-Allow-Origin: *
Access-Control-Request-Method: *
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Mon, 15 Jan 2018 22:52:34 GMT
Server: Cowboy
Strict-Transport-Security: max-age=7776000
Via: 1.1 vegur
Www-Authenticate: hawk
X-Powered-By: Express

{
  "code": "AuthenticationFailed",
  "message": "Bad Request: Bad attribute value: id\n----\nmethod:     rerunTask\nerrorCode:  AuthenticationFailed\nstatusCode: 401\ntime:       2018-01-15T22:52:34.390Z",
  "requestInfo": {
    "method": "rerunTask",
    "params": {
      "taskId": "JR-H-z2RT9uz75c96BR_-Q"
    },
    "payload": {},
    "time": "2018-01-15T22:52:34.390Z"
  }
}
Usage:
  taskcluster task rerun <taskId> [flags]`

The issue here is that
export TASKCLUSTER_CLIENT_ID='mozilla-ldap/<my ldap id>/cli'
export TASKCLUSTER_ACCESS_TOKEN='looksLikeARealToken'
uses "export" which is not a known command on Windows where "set" should be used. One can test the variables with "echo %TASKCLUSTER_CLIENT_ID%" to see that they are not set (compare e.g. with "echo %PATH%).

**Comment by djmitche** [comment]
The other issue is that just printing `set TASKCLUSTER_CLIENT_ID=..` to the console won't actually set that value, either.  On UNIX, we run this as

```shell
eval $(taskcluster signin)
```

which sets those environment variables in the running shell. I don't see anything in the transcript above that attempts to set variables (with `export` or `set`).  How would we do something like that on Windows?  @petemoore do you have any ideas?

**Comment by Archaeopteryx** [comment]
Please ignore the issue, the "export" message was a red herring. I tried rerunning a task now and it returned "pending". But one of the Softvision sheriffs tried to log in earlier this week and also got the auth failure: https://irccloud.mozilla.com/file/vsoqv8xJ/image.png
Bad timing? For the softvision sheriffs, do you they require additional scopes in addition to https://wiki.mozilla.org/Sheriffing/How_To/Getting_started_as_a_sheriff#Permissions to rerun jobs?

**Comment by djmitche** [comment]
So I think we still have an issue that we don't have a Windows equivalent to `eval $(taskcluster signin)`.  Perhaps @petemoore or @grenade can chime in with some ideas.

The other issue is, it seems in some cases that the HTTP server embedded in the command does not make an HTTP reply, which leaves Firefox hanging at "contacting localhost".  I've created #187 for that.

**Comment by djmitche** [comment]
It looks like this is a false alarm -- users here are using the msys bash shell, so `eval` does work.  Just, @Archaeopteryx didn't use it :)
