### ISSUE TITLE
Creation of new client during taskcluster signin hangs after clicking "Create client" with "Connecting to localhost...", at least in Ubuntu VM

### ISSUE THREAD

**Issue by Archaeopteryx** [taskcluster/taskcluster-cli#186]
The Softvision sheriffs and I have Ubuntu VMs which they use for the tree management. We have the Linux x64 binary version a593372 and if we run `taskcluster signin` and click the `Create client` button, the network message "Connecting to localhost" is shown as a tooltip at the bottom left by the browser, but it gets stuck there and doesn't show the "successfully logged in" message. At least five people have tried this and failed.
Attila from Softvision compiled the binary from source and still hit the same issue.
Launching dummy-web-server.py works as expected.

**Comment by Archaeopteryx** [comment]
Dustin helped on vidyo: the credentials mentioned in the shell when one closes the waiting browser are actually valid but have to be evaled (in contrast to Windows). `eval $(taskcluster signin)` followed by `taskcluster task rerun ataskid` returns `pending`.
The localhost runs but doesn't return anything.

**Comment by djmitche** [comment]
STR:

1. `taskcluster signin`
1. Click UI buttons
1. Firefox says "connecting to localhost", nothing further happens; taskcluster-signin is still running in the shell
1. Close the Firefox tab/window
1. Taskcluster-signin returns, displaying credentials

So it seems Firefox is successfully sending the credentials to taskcluster-signin, but that process is not sending an HTTP response to the browser, so the final page is never displayed.

**Comment by djmitche** [comment]
This was fixed in #187
