### ISSUE TITLE
Fail if TASKCLUSTER_ACCESS_TOKEN is set, but TASKCLUSTER_CLIENT_ID is empty

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#191]
Right now this gives an unusual error - https://bugzilla.mozilla.org/show_bug.cgi?id=1461579

We should check that both of these values are set, and if one is set but not the other, fail with a useful error message.

**Comment by palash25** [comment]
Hey there I'm a newbie Gopher.

Is the required change needed to be done here `config/init.go/Setup` ? I see that it already checks for both the ID & TOKEN lookup status so I guess I would only need to add an else there?

**Comment by djmitche** [comment]
I'm new to Go, too, more-or-less :)

Yes, I think that's correct.

**Comment by palash25** [comment]
Ok I'll try to give it a shot. Will send a PR in a few days :smile:
