### ISSUE TITLE
Running make updates vendor.json

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#198]
In #192 and #197 we saw that running 'make' resulted in diffs to `vendor.json`.  It's not too hard to back these out, but it's a drag on contributions and seems wrong.

@petemoore do you have any idea why this would happen, and how we could fix it?

**Comment by petemoore** [comment]
I suspect the answer is to adopt [go dep](https://github.com/golang/dep).

**Comment by petemoore** [comment]
> OK, so it's basically a `govendor` bug?

Yes it is kardianos/govendor#233. The `govendor` author himself [suggests using vgo (a.k.a. go modules)](https://github.com/kardianos/govendor/issues/233#issuecomment-403084088) to workaround the bug.

**Comment by djmitche** [comment]
Cool, thanks!  We'll ignore it here in tc-cli for now.
