### ISSUE TITLE
All commands should accept TASKCLUSTER_ROOT_URL

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#199]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1460012

As part of the ongoing "redeployability" project, a user needs one more piece of information to connect to a Taskcluster service: a root URL.  For the current Taskcluster, that's `https://taskcluster.net`, but for example for another cluster that's `https://taskcluster.imbstack.com`.  #192 addressed a little bit of this: the `taskcluster signin` command gets a root URL configuration and uses it to figure out what loginUrl to open, and also outputs that as an environment variable for the user.

The next step is to make all of the other commands in this repo also use TASKCLUSTER_ROOT_URL.  That will entail moving the rootUrl option to the global options for all commands (where clientId and accessToken are defined), and then using the rootUrl along with https://github.com/taskcluster/taskcluster-lib-urls to call the proper APIs.

@palash25 does this look like something you could work on?  It can probably be done in parts:
 * move the configuration (to the file you just modified in #197)
 * use the rootUrl for the `api` commands
 * use the rootUrl for all other commands (this will require updating https://github.com/taskcluster/taskcluster-client-go, if someone else doesn't get to it first).

**Comment by palash25** [comment]
Sure I'll look into it

**Comment by djmitche** [comment]
This got handled while moving to the monorepo.
