### ISSUE TITLE
Redirect error messages to stderr

### ISSUE THREAD

**Issue by walac** [taskcluster/taskcluster-cli#20]
Currently, all errors message go to `os.Stdout`. We should use `fmt.Fprintf` to redirect them to `os.Stderr`.

**Comment by ApheleiaS** [comment]
Hello, 
Please assign me to this bug. I am interested in participating in outreachy this round. 
Thanks.

**Comment by iamneha** [comment]
@ApheleiaS I almost solved this bug I would like to request you to please ask for another bug and I am sorry that I forgot to ask mentor to assign this to me.

@walac can you assign me this bug

**Comment by ApheleiaS** [comment]
@iamneha  I solved this bug quite a bit as well. So I am not sure.  Anyhow you should make your PR if you are done. That way we can learn from each others code and devs can merge the one which looks better :)

**Comment by walac** [comment]
@iamneha sorry, but @ApheleiaS requested bug assignment first. We are working this week to get more good-first-bugs, as the number of applicants is way beyond our expectations.

**Comment by yannlandry** [comment]
Started working on this issue. Seems like it's gonna be a tedious task of search and replace - wish me luck.
