### ISSUE TITLE
Error messages should print on stderr, not stdout

### ISSUE THREAD

**Issue by jhford** [taskcluster/taskcluster-cli#200]
```
jhford-desktop:~/taskcluster/taskcluster-queue $ `taskcluster signin --scopes assume:project:taskcluster:tests:taskcluster-queue`
-bash: Either: command not found
jhford-desktop:~/taskcluster/taskcluster-queue $ taskcluster signin --scopes assume:project:taskcluster:tests:taskcluster-queue
Either ClientID or Access Token not set
```

We should probably write this error message to stderr.  This might be related to https://github.com/taskcluster/taskcluster-cli/pull/197

@palash25 I was told you might be interested in making this change :)

**Comment by palash25** [comment]
Sure @jhford I'm a little busy right now but I will give it a crack next week

**Comment by djmitche** [comment]
The other error in that file should also go to stderr -- so this isn't a new bug :)
