### ISSUE TITLE
taskcluster-cli should be installable through go get

### ISSUE THREAD

**Issue by jhford** [taskcluster/taskcluster-cli#206]
A developer with a working go toolchain should be able to type in "go get github.com/taskcluster/taskcluster-cli" and have a working copy of the CLI built and installed.  That's currently not working, I suspect because of the renames of the various client modules.

**Comment by knrt10** [comment]
@jhford I would like to work on this issue.

**Comment by jhford** [comment]
@knrt10 hey, that's cool!  The first thing that I'd recommend is building it locally if you haven't already.  I suspect that this is not the case because dependencies aren't up to date.  We use a vendored copy of some dependencies, and those dependencies have had breaking changes landed since they were added to the vendoring manifest.

**Comment by djmitche** [comment]
This is the case now.
