### ISSUE TITLE
Add test case for the credentials module

### ISSUE THREAD

**Issue by walac** [taskcluster/taskcluster-cli#21]
Taskcluster uses [Hawk]() for authentication under the hood. The [credentials module]() provides an interface for taskcluster authentication. Unfortunately, it doesn't have any unit test case. Implementing a test case for follows these steps:

* Create a `Credentials` object with `ClientID = tester` and `AccessToken = no-secret`
* Create a request to [testAuthenticate](https://docs.taskcluster.net/reference/platform/auth/api-docs#testAuthenticate)
* Sign it using `SignRequest`
* Perform the request and check it was successful

**Comment by nanjekyejoannah** [comment]
Hello ...

Kindly assign me this issue..thanks

**Comment by walac** [comment]
@nanjekyejoannah I sent you an invitation to taskcluster-cli-contributors team, once you accept the invite, I assign you to the bug
