### ISSUE TITLE
Implement command to download an artifact

### ISSUE THREAD

**Issue by walac** [taskcluster/taskcluster-cli#22]
An artifact is a result of of task. It can be a binary file, a test report, a log, etc. We need to implement a command to download an artifact:

``` shell
taskcluster download <taskId> <runId> <artifact>
taskcluster download <taskId> <artifact>
taskcluster download --index <indexNamespace> <artifact>
```

When `<runId>` is omitted, it should download artifacts from latest `runId`.
- Automatic retries
- [Exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff)
- Check content-length
- Follow redirects
- Enforce HTTPS
- Stream result to a file
- gzip decode if content-encoding: gzip

Please check https://godoc.org/github.com/taskcluster/taskcluster-client-go/queue#Queue.GetArtifact_SignedURL

If <artifact> is omitted, it should list all artifacts.

**Comment by petemoore** [comment]
See [example usage of queue.GetArtifact_SignedURL](https://sourcegraph.com/github.com/taskcluster/taskcluster-client-go/-/info/GoPackage/github.com/taskcluster/taskcluster-client-go/queue/-/Queue/GetArtifact_SignedURL). You'll need to first retrieve a signed url (also works with public artifacts) and then download from there. Consider using [httpbackoff](https://github.com/taskcluster/httpbackoff) library.

**Comment by walac** [comment]
Also see [got package](https://github.com/taskcluster/go-got)

**Comment by alexandrasp** [comment]
Hey @walac and @petemoore, can you assign me this bug? :)

**Comment by iamneha** [comment]
assign me this bug

**Comment by petemoore** [comment]
I think it makes more sense for this to be a standalone tool, it could be needed by tasks, and I think it does not make sense for tasks to have to install the CLI, which is a dev tool, as I see it (for example, a task environment should not need a tool which allows you to open a VNC connection to the task environment via VNC).

Let's at least keep a separation between tools that serve developers, with tools that serve tasks - and I believe for the most part taskcluster-cli is intended to be a dev tool.

**Comment by petemoore** [comment]
Also note, jhford is already working on a standalone tool for uploading/downloading artifacts.

**Comment by djmitche** [comment]
Indeed, this functionality will be a part of https://groups.google.com/forum/#!topic/mozilla.tools.taskcluster/5ISrXVJUl1s
