### ISSUE TITLE
Add from-now cli command

### ISSUE THREAD

**Issue by walac** [taskcluster/taskcluster-cli#24]
``` shell
taskcluster-cli from-now
```
- [Background](https://github.com/taskcluster/taskcluster-client#relative-date-time-utilities)
- [Reference implementation](https://github.com/taskcluster/taskcluster-client/blob/master/lib/utils.js#L15)

Example:

``` shell
taskcluster-cli from-now '2 days'
```

**Comment by alessbn** [comment]
Hi! Can anyone assign me this bug?

**Comment by walac** [comment]
@jonasfj Can you assign @alessbn to this bug? I can't. Not sure if it because I don't have powers or github doesn't allow.

@alessbn consider yourself assigned to this bug, anyway.

**Comment by jonasfj** [comment]
@walac, you can't assign people who aren't member of the organization.
Feel free to create a team for `taskcluster-cli-contributors` or something, and add this repo.

**Comment by djmitche** [comment]
This would be useful in generating new task definitions:
```
cat <<EOF | taskcluster queue createTask $taskId
{
...
  expires: "$(taskcluster from-now '2 days')",
...
}
EOF
