### ISSUE TITLE
Integrate with Travis-CI

### ISSUE THREAD

**Issue by walac** [taskcluster/taskcluster-cli#25]
[Travis](https://travis-ci.org/) is a Continuous Integration system aimed for small and medium size projects. `taskcluster-ci` doesn't run any tests or linter on pushes and  pull request, which is sad. We would like to use travis to run:
1. `go test -v -race`
2. `go fmt -s -w` and then check if we have uncommited changes
3 `gometalinter --disable-all --enable=gotype --enable=golint --enable=deadcode --enable=staticcheck --enable=deadcode --enable=misspell --enable=vet --enable=vetshadow --enable=gosimple --enable=varcheck --enable=aligncheck --enable=errcheck --enable=ineffassign --enable=unconvert --enable=staticcheck  --enable=goimports --enable=unused`

You can see [how we run `go test` and `go fmt` in taskcluster-worker](https://github.com/taskcluster/taskcluster-worker/blob/master/Makefile).

This should run on Linux, MacOSX and Windows. Ideally we should run under go 1.7, but Travis doesn't support 1.7 version, so it is ok to use 1.6 for now. But if a keen to make 1.7 working, you can see [how we do it in taskcluster-worker](https://github.com/taskcluster/taskcluster-worker/blob/master/.travis.yml) and do something like that. 

You can start fixing errors reported by `gometalinter` and then add travis.

**Comment by somya-anand** [comment]
Hi,
Can you assign me this bug? Thanks

**Comment by ibrahimelbanna** [comment]
Hi ,
Can you assign me this bug ?

**Comment by walac** [comment]
@ibrahimelbanna sorry, @somya-anand took it already, would you be interested on working on #18?

**Comment by ibrahimelbanna** [comment]
Yes I am interested on working on this bug  @walac

**Comment by djmitche** [comment]
I set up a very simple `.travis.yml`, which should be sufficient.  We should aim to test this tool with TaskCluster itself.
