### ISSUE TITLE
Add CLI command to upload/download to/from S3

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-cli#28]
Using `auth.awsS3Credentials` takes taskcluster credentials and returns temporary STS credentials for S3.
It would be cool if we had a command like `taskcluster s3 copy ./myfile.txt s3://<bucket>/<prefix>`
that could get temp creds from auth and use those to upload a file to S3.
Obivously, it would have to do retries with exponential back-off, ideally also multi-part upload for large files.
Detect mimetype based on file extension... Provide content-md5 for S3 to verify.

See: https://docs.taskcluster.net/reference/platform/auth/api-docs#awsS3Credentials

Further steps could include:
- Download file
- Upload a folder of files
- Download a folder of files
- Adding extra headers like `x-amz-meta-content-sha256` for integrity checks on downloads

**Comment by nikinath** [comment]
I'd like to work on this bug. Can I please get assigned?
Thank you!

**Comment by djmitche** [comment]
I don't think we should implement this feature.  We currently have to manually whitelist all s3 buckets to which auth can grant access, which severely limits the utility of a feature like this.
