### ISSUE TITLE
`taskcluster status` command to list status from all services

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-cli#29]
All or most of our API services have a `status` end-point...

Based on JSON from: https://github.com/taskcluster/taskcluster-cli/tree/master/apis/definitions

We should write a command that uses this JSON to for each service print:

```
service        status
queue          up
auth             up
...
```

By calling the status endpoint to verify that the services are up and running.

**Comment by owlishDeveloper** [comment]
Hi! May I grab this bug? Thanks!

**Comment by walac** [comment]
Example: https://queue.taskcluster.net/v1/ping is an endpoint to check status of the queue service. This bug consists of creating a new `CommandProvider` status, that will use this endpoint on taskcluster services to retrieve the statuses.

Command summary:

```shell
Usage:
  taskcluster-cli status [--services=<list>]
Options:
  -s <list>, --services=<list>   comma separated services list to retrieve status from. [default: queue,auth,aws-provisioner,events,index,scheduler,secrets]
```

You can look at a sample implementation [here](https://github.com/taskcluster/taskcluster-tools/blob/master/status/status.jsx)

**Comment by jonasfj** [comment]
I suggest:
```
Usage:
  taskcluster-cli status [<service>...]
```

Default to all serivces if none are specified.

**Comment by djmitche** [comment]
I don't think this is a really useful tool -- it's easy enough to curl that endpoint if you really want to know, and otherwise users will look at the status page for that information.
