### ISSUE TITLE
Add scope-check command

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-cli#30]
In taskcluster we use scopes for authorization, see:
https://docs.taskcluster.net/presentations/scopes/
(formal definition and examples)

It would nice if we had a command like:

``` sh
$ taskcluster scope-check scopeA scopeB... satisfies scopeC scopeD...
```

Which will then determine if scopes `scopeA, scopeB, ...` satisfies `scopeC, scopeD, ...`, the argument `satisfies` would be a keyword in this command.

**Example:s**

``` sh
$ taskcluster scope-check queue:ping satisfies queue:ping # exit code 0
YES

$ taskcluster scope-check queue:ping satisfies queue:test # exit code 1
NO, missing:
 - queue:test

$ taskcluster scope-check 'queue:*' test:scope other-scope satisfies queue:test # exit code 0
YES

$ taskcluster scope-check 'queue:*' satisfies other-scope # exit code 1
NO, missing:
 - queue:*

$ taskcluster scope-check 'queue:*' satisfies 'queue:create-ta*' # exit code 0
YES 
```

Maybe the output messages could be formatted better...

Note: Step one is to just do simple string comparison. Next step would then be to take the left-hand-side scopes and expand them using:
https://docs.taskcluster.net/reference/platform/auth/api-docs#expandScopes

Any scope on the form `assume:...` may be expanded. On the right handside expansion is unnecessary since if `assume:...` is satisfied, then any expansion on the left-hand-side would also include scopes `assume:...` expanded to.

**Comment by nanjekyejoannah** [comment]
Hi team

Kindly assign me to this issue..thanks

**Comment by djmitche** [comment]
Scope checking is a security-sensitive operation.

As such, it shouldn't be done in shell!

So, I don't think we should add this feature.
