### ISSUE TITLE
Add expand-scopes command

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-cli#31]
In taskcluster we use scopes for authorization, see:
https://docs.taskcluster.net/presentations/scopes/
(formal definition and examples)

The taskcluster-auth service maintains roles... a role is effectively just a mapping from a scope on the form `assume:...` to a set of scopes that the role grants.

Example:
`assume:project:taskcluster:tutorial` grants scopes listed here:
https://tools.taskcluster.net/auth/roles/#project:taskcluster:tutorial

A command like this:

``` sh
$ taskcluster expand-scopes assume:project:taskcluster:tutorial
assume:project:taskcluster:tutorial
queue:create-task:aws-provisioner-v1/tutorial
secrets:get:garbage/*
secrets:set:garbage/*
```

Would be pretty nice to have. The API has a method for expanding scopes here:
https://docs.taskcluster.net/reference/platform/auth/api-docs#expandScopes

So this is really just parsing arguments, call API and print the result line by line.

**Comment by nikinath** [comment]
According to the getting started link: https://public.etherpad-mozilla.org/p/taskcluster-cli-applicants-getting-started, we can be assigned to a new bug if we open a PR for the one we are currently working on.

Is it okay if I am assigned to this bug? I will continue working on #33 too.

**Comment by nanjekyejoannah** [comment]
Hello nikinath

I had solved this and was thinking of opening a PR for two since issue #30 is related to this issue because it involves expanding scopes but if you still want to continue working on it . I have no problem since I hadnt notified that am working on it.

**Comment by nikinath** [comment]
@nanjekyejoannah I have already solved this issue and thus I'd like to send in a PR. I hope that's okay! :)
Sorry for the trouble!

**Comment by djmitche** [comment]
There is already an API call for this (`taskcluster auth expandScopes`), so I don't think we need a distinct command.
