### ISSUE TITLE
Add `taskcluster completion` command dumping auto-complete script for bash

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-cli#32]
I'm not 100% sure how to do this.. There is probably some docs to read :)

But it is possible to do auto-completion for a custom command, I suspect that we can auto-generate such auto-completion logic from the docopt strings and generate a command that can install the auto-complete script in `/etc/bash_completion.d/taskcluster` that would be pretty cool.

**Comment by jonasfj** [comment]
See:
https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion.html
https://github.com/scop/bash-completion

I didn't read these sources, but they would definitely be needed to do something like this.
And initial hack here might just be auto-complete the sub-commands.

**Comment by djmitche** [comment]
Ah, same bug as #64
