### ISSUE TITLE
Run tests using taskcluster-github

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#47]
We have a basic `.travis.yml` set up in #46, but we should be using taskcluster via taskcluster-github instead of travis.  And doing releases (binary builds) when we push a new tag.

**Comment by djmitche** [comment]
This should also include (see #25)
 * code coverage analysis
 * go fmt 
 * go test -v race
 * shell tests (actually running `./taskcluster` and making sure it behaves correctly)

**Comment by djmitche** [comment]
A .taskcluster.yml landed in #89.  I'd suggest breaking the rest of the items in the comment above out into separate issues, then closing this one.

**Comment by lteigrob** [comment]
Issue 92 is created to add these things

**Comment by djmitche** [comment]
That sounds good, yeah.  Even #92 might get broken further down if one of the pieces turns out to be hard.

**Comment by lteigrob** [comment]
Okay, thanks
