### ISSUE TITLE
Automatically export documentation for taskcluster-docs on release

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#48]
We have `taskcluster-lib-docs` for JS services, which can upload a tarball containing documentation.  Let's build a similar thing for Go (but omitting the API references and exchanges, since we don't implement TaskCluster HTTP APIs in Go), so that we can upload documentation about all of the tc-cli options to taskcluster-docs, too.

**Comment by jonasfj** [comment]
Please consider making this a golang library, so we can reuse it for uploading docs from taskcluster-worker too...

This would effectively be uploading the docs/ folder, and possibly some code to generate docs for it too..

**Comment by gregarndt** [comment]
Looks like this commit is what we were looking for:
https://github.com/taskcluster/taskcluster-cli/commit/505bd7a101c2a702832147deb8ceee5e8a5b348b

However, it does seem that if the release task fails, document will still be updated.

**Comment by djmitche** [comment]
Yep, and it's uploading https://docs.taskcluster.net/reference/libraries/taskcluster-cli

It's not versioned, but we don't really version anything anyway :)
