### ISSUE TITLE
Build releases using taskcluster-github

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#49]
When we create a new Github release of taskcluster-cli, tc-github should automatically build and upload binaries for the various platforms we support, and make them available for users.

**Comment by djmitche** [comment]
I can get this working for linux releases, and then hand off to @t0xicCode to set up other platforms.  Hopefully we can cross-compile for those platforms!

**Comment by djmitche** [comment]
There's no way to upload those artifacts to a github release, which is too bad because that'd be the most convenient!
  https://bugzilla.mozilla.org/show_bug.cgi?id=1344913

**Comment by djmitche** [comment]
My current plan is this:
 * react to "release" events and build the corresponding tag
 * on release, upload the resulting binary to an S3 bucket with an appropriately versioned name, and also update a "latest" value
 * point to the "latest" URL from the README

After #107, any cross-compilations should be easy to include in this process, if you want to get started on that @t0xicCode

**Comment by djmitche** [comment]
(The part remaining for me is points 2 and 3)

**Comment by djmitche** [comment]
Working on the second point, I got stuck at #122.

**Comment by djmitche** [comment]
OK, that's done -- all that's left is the cross-compilation!

**Comment by t0xicCode** [comment]
Perfect! I guess I'll take over from here :)
