### ISSUE TITLE
Tail the log of a running task

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#51]
```
taskcluster task-log <taskId>
```
should output the logs for the given taskId as they are generated, and exit when the task completes.

**Comment by t0xicCode** [comment]
Should this be listed under `taskcluster task tail <taskId>` instead? To group all actions related to _tasks_ together?

**Comment by djmitche** [comment]
Yes, but let's not worry about that until the subcommand support is in place.  It should be relatively easy to move it at that point.

**Comment by djmitche** [comment]
This is landed now in #97. There is some follow-on mentioned there that @AyubMohamed will be handling.
