### ISSUE TITLE
Better support for users with `taskcluster signin`

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#53]
```
dustin@lamport ~/go/src/github.com/taskcluster/taskcluster-cli [master] $ ./taskcluster signin
Starting
Listening for a callback on: http://localhost:37706
```
..and it hangs there.  What do I do?  Some better documentation for the user would be helpful :)

**Comment by djmitche** [comment]
Also, documenting where the results of that signin are stored would be good!

**Comment by lteigrob** [comment]
My first thought is: 

"Opening tab in browser. If tab does not open automatically please go to https://login.taskcluster.net/" (as a link)

Is that the sort of thing we want there?

**Comment by djmitche** [comment]
Indeed!  In fact, there are some extra fields after `.net` that are important.

The other bit is, the tool assumes that "localhost" will resolve to the host where you ran `taskcluster`, which isn't necessarily the case.  So we might think of a way to allow the host's full name there, instead (maybe with a `-h <hostname>` option?)

But let's do the first part, that you suggested, first.  The second part may only be a problem for me :)

**Comment by lteigrob** [comment]
Deal :)

**Comment by lteigrob** [comment]
I've got a signin_support branch started. What sort of fields do I need?

**Comment by djmitche** [comment]
It adds target and description [here](https://github.com/taskcluster/taskcluster-cli/blob/3125d2f1b331e87e0e1ecf854a35b5c9b3833165/config/signin.go#L137), so it's that full URL that's required.

**Comment by lteigrob** [comment]
Ooooh. K, thank you

**Comment by djmitche** [comment]
I think we'll accomplish this with PCKE, someday..
