### ISSUE TITLE
Better help output for API commands

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#55]
```
./taskcluster auth --help
```
currently shows the description of the auth API (the top of https://docs.taskcluster.net/reference/platform/auth/references/api)  However,
```
./taskcluster auth listClients --help
```
does not show the listClients description.  It should!  It should also show the payload and response schemas.

**Comment by jonasfj** [comment]
Interface should work for both `taskcluster auth help listClients` and `taskcluster auth listClients --help`

**Comment by AyubMohamed** [comment]
I think the enabling of subcommands would fix this issue. See https://github.com/taskcluster/taskcluster-cli/issues/76

**Comment by djmitche** [comment]
This seems fixed.
