### ISSUE TITLE
Command to wait for a task to complete

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#56]
It's quite possible that users will write scripts that start a task, then wait for it to complete.  Something like:
```
taskcluster api queue createTask $TASKID <task.json
taskcluster task await-completion $TASKID
```

**Comment by t0xicCode** [comment]
This should be covered by #81, but a dedicated command to await completion or exception could be useful.

**Comment by t0xicCode** [comment]
Covered in #81. Should we close this?

**Comment by djmitche** [comment]
Agreed.
