### ISSUE TITLE
Support uploading files to and downloading files from a loaner

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#57]
This would be an extension of #54 to also support transferring files to/from the loaner.

There is no `scp` or anything like that on the loaner, so this will require figuring out how to handle this on the loaner side.  Maybe Perhaps use: https://github.com/taskcluster/file-browser-go (author is planning to have included in docker-worker, and writing a JS API for using it)

**Comment by jonasfj** [comment]
other options is to rely on busybox being present in a predefined location, docker-worker does that... ask me for details..

**Comment by jonasfj** [comment]
@ckousik, this is an interesting use-case for the file-browser-go, that doesn't involve making UI.
Note: it's blocked by #54 as we don't have a golang implementation of a client for docker-exec-websocket-server.
