### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#58]
It would be nice for users to always have the latest and greatest taskcluster client.  We could do this a few ways:

1. Build apt, yum, and homebrew repositories and automatically upload releases to them, so users can update the "normal" way
2. Only update the API definitions, caching them in ~/.taskcluster.  Then `taskcluster api` would always be up-to-date, but the other subcommands would only get updates when the user manually downloads a new version.
3. Use some service like https://equinox.io/

There are some serious security concerns with options 1 and 3, of course!

**Comment by jonasfj** [comment]
3. Would also be possible without the service, using: https://github.com/inconshreveable/go-update
We would simply build and sign the updates from a taskcluster-github command, then have that task indexed under a stable namespace which can then be used for find the latest update.

This would actually be fairly simple.
