### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by lteigrob** [taskcluster/taskcluster-cli#64]
Users will want to be able to hit tab to complete a command, or to see a list of command options if there is more than one available.

**Comment by lteigrob** [comment]
Bash completion tutorial I'll look through:
https://debian-administration.org/article/316/An_introduction_to_bash_completion_part_1
-For a generic OS, adding to this functionality can be done with an extra file /etc/bash_completion.d... How to add to the ./taskcluster commands in a similar way?

**Comment by djmitche** [comment]
Some notes from @jonasfj:

Parse the docopt strings and generate script for bash completion
* Command to (un/re)install bash completion
* Completion script should call “eval `taskcluster bash-completion`” to ensure there is no need to reinstall when taskcluster-cli is auto updated.
* (taskcluster bash-completion should NOT trigger auto-update, or at-least not block on auto-update)
* Perhaps make some security considerations about this :)

**Comment by lteigrob** [comment]
Right now working on just getting a useful tab completion on my own computer, before figuring out where in the actual taskcluster setup this might be incorporated.

Using a template, I've created my own tab completion. Obviously the word "taskcluster" can replace "foo" and I could put in to "opts" our help topics, so it can fake usefulness. Right now this doesn't work as we'd like for the actual execution of ./taskcluster [tab], only for taskcluster --[tab].  

To work on right away:
1. Get this to work as completion for the executable
2. Complete in a more generic way ie filling in partially written words
And then:
3. Be able to pull from the list of options directly instead of having to type them all in, so it will update automatically if commands are added
4. Incorporate into the tc setup so it can be included in download, with the considerations noted by jonasfj


Reference notes for myself:

_foo() 
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts="--help --verbose --version"

    if [[ ${cur} == -* ]] ; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
    fi
}
complete -F _foo foo

This gets saved as /etc/bash_completion.d/foo and must be sourced with . /etc/bash_completion.d/foo before use as foo --[tab]. (All straight from the tutorial)

**Comment by lteigrob** [comment]
Setting this aside for now, but for future reference: Point 1 above doesn't seem to be a problem with the way the compgen command works. The method in the tutorial can be made to work, with a list (the help list) that can be pulled from the names slice in main.go. Maybe subcommands can be extracted similarly, but I haven't found that yet. This would be the easiest solution. Harder solution: Using Parse (docopt) for this purpose might work, but would take more time to figure out. But if we can work around that for this purpose we might not need it in main at all (?)

**Comment by jonasfj** [comment]
So maybe docopt isn't the best way for plugins to specify how they take input... It also doesn't make it easy to know about subcommands...

Perhaps we should use a structured format instead, the generate the usage string from that format...

**Comment by yannlandry** [comment]
I don't know how far down this is in @lteigrob's list of things to do, but here's a link for whenever this happens:

https://github.com/spf13/cobra/blob/master/bash_completions.md

**Comment by lteigrob** [comment]
Yeah definitely! I've been playing around with this. Earlier in the semester I had some bash completion working for little testers. Now I'm just trying to convert their command (in that link) to produce such a bash file for our own stuff. 

Am I right in thinking that this:
https://github.com/taskcluster/taskcluster-cli/blob/e0b23844e891bd77a29ad1c83ca298178aba8790/apis/provider.go#L51

is our version of this:
https://github.com/kubernetes/kubernetes/blob/0a6d82d8e72469bc2320c4d87102789ec86ce71c/pkg/kubectl/cmd/cmd.go#L223
?

**Comment by djmitche** [comment]
To my admittedly untrained eye, yes :)

**Comment by lteigrob** [comment]
lol I'll take it. I think that'll get me headed in the right direction at least

**Comment by t0xicCode** [comment]
Is it completed?

**Comment by djmitche** [comment]
Hit tab and find out?  Only sorta kidding :)

**Comment by yannlandry** [comment]
I don't remember anything being done in that regard, so unless @lteigrob has some code tucked away somewhere, I'd guess it never started :wink:

**Comment by jonasfj** [comment]
I got to `taskcluster api index ping` using tab :)

So yeah, I think it's working...

**Comment by t0xicCode** [comment]
Yeah, cobra should go it all automagically :)
