### ISSUE TITLE
Automatically update the API definitions

### ISSUE THREAD

**Issue by t0xicCode** [taskcluster/taskcluster-cli#66]
The service definitions are fetched from the schema server and turned into go code through `go generate` .

Currently this is a manual process, with the results checked in when we remember to do so. We have a few ideas regarding how to make this better.

The first idea is to have a scheduled task in taskcluster to run `go generate` and generate a PR if there are changes.

The other option is to run `go generate` only as part of the release process, the generated binaries would have the latest definitions, but the repository would have old versions checked-in.

**Comment by petemoore** [comment]
@t0xicCode what will be the mechanism to upgrade installed clients?

For example, if I have taskcluster-cli installed, and a schema is updated, and then a new release is made, how will my client notice that it is out-of-date and upgrade to the latest version?

**Comment by djmitche** [comment]
@petemoore that's #58.

**Comment by yannlandry** [comment]
Shouldn't the generated code be fetched and generated a compile-time? Could we embed that into the Makefile, just like we do for vendoring?

We might also want to add a mechanism that skips generation if everything is already up-to-date. Then include **apis/services.go** in the **/.gitignore**.

**Comment by djmitche** [comment]
I like having two steps, for a few reasons:
* An application's behavior shouldn't change dynamically during development
* Compiling shouldn't require Internet access and functional S3
* APIs are fetched over http, so we need to review the changes before using them to avoid the risk of MITM attacks

**Comment by djmitche** [comment]
This is generated in `yarn generate` now.
