### ISSUE TITLE
Find a way to get metadata about command-line options

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#68]
For command-line completion (#64), we need information on the available command-line options.

Docopt, as-written, doesn't support that: its `Parse` method just interprets the usage strings, then returns the result of parsing the command line.  It doesn't give any information from its interpretation of the usage strings.

Options:
 1. Fork docopt to return that information (if this isn't too hard) (and if it makes sense, make a PR for docopt in case they want to adopt it)
 1. Find another command-line option library that will give us the data we need
 1. Write our own command-line option library

**Comment by t0xicCode** [comment]
Should this be closed by #99?

**Comment by djmitche** [comment]
Yeah, I think #99 represents option 2 :)
