### ISSUE TITLE
Enable the implementation of subcommands

### ISSUE THREAD

**Issue by yannlandry** [taskcluster/taskcluster-cli#76]
As of now, when we need to add a command, we create an implementation of the `CommandProvider` interface, and register it. We have already added a few commands using this:

- `taskcluster help`
- `taskcluster from-now [...]`
- and others

However, there are commands that have their own subcommands. `taskcluster api [...]` is an example of this. Another example:

- `taskcluster slugid v4`
- `taskcluster slugid nice`
- `taskcluster slugid decode <slug>`
- `taskcluster slugid encode <uuid>`

In this case, the best option has been to implement all four subcommands manually as part of the `slugid` command. It would be preferable to be able to have one implementation of `CommandProvider` for each subcommand and ideally be able to register it _under_ the `slugid` command.

[It seems docopt is able to parse subcommands](https://github.com/docopt/docopt/issues/4), so this is good.

This will be pretty much essential to all the `taskcluster api` subcommands.

**Comment by yannlandry** [comment]
As of now, I'm on it. I'll need to figure out more than a few things but once we're there we should be able to register commands in the form of a tree.

**Comment by yannlandry** [comment]
Okay, I've spent a good deal of time thinking and reading up on other issues [...] and it seems the best solution would be to design a custom parser for our needs.

Here is the idea I came up with. Assume the following command/subcommand structure:

       taskcluster
       |         |
    help     +---slugid------+
            /    |    |       \
          v4  encode  decode  nice

The new parser would make it easy to create a `CommandProvider` for each command and each of its subcommands.

To register `taskcluster slugid`, I would do `extpoints.Get("taskcluster").Get("slugid").Register(slugid{})`. To register subcommand `encode` under `slugid`, I would do `extpoints.Get("taskcluster").Get("slugid").Get("encode").Register(encode{})`.

It would be possible to register a `CommandProvider` at each node/leaf of the tree (including the root `taskcluster` itself), and also to add code to be executed everytime a command under `slugid` is called.

Obviously, there would also be options to add flags and options to each command and sub*command.

**Comment by yannlandry** [comment]
Currently trying out github.com/alecthomas/kingpin as @t0xicCode suggested to see if it would work for us.

**Comment by yannlandry** [comment]
Going custom. Built a command-definition system yesterday, and soon we'll have a parser/framework to go with that. See it in branch _subcommands_.

**Comment by yannlandry** [comment]
_Today's update:_

Added/fixed/changed a few things, and moved the code to a new package named `commander`.

**Comment by t0xicCode** [comment]
https://github.com/spf13/cobra?

**Comment by yannlandry** [comment]
Didn't see this one while looking for possible packages to use... some features look similar, interestingly. I didn't look into it too much, however at this point I've got pretty much everything down, including the parser.

**Comment by t0xicCode** [comment]
While I don't want you to lose all the work you did, would it make sense to still try the library? If we can use an external library that we don't have to maintain and support, that'd leave more time for use to work on the specific features of the tool.

And cobra has bash completion "for free" as well 😄

**Comment by djmitche** [comment]
My notes from the meeting on Friday indicate we decided:
 * spend a week working to use Cobra
 * we may be able to move to the new system subcommand-by-subcommand.  @yannlandry will work on a transition plan

**Comment by yannlandry** [comment]
Pull request for step 1 online.

See **[the transition plan](https://github.com/taskcluster/taskcluster-cli/wiki/Transition-plan-from-docopt-to-cobra)** for more details.

**Comment by t0xicCode** [comment]
Closed by #99.
