### ISSUE TITLE
Replace javascript taskcluster-cli (Allow task creation, scheduling, tailing)

### ISSUE THREAD

**Issue by t0xicCode** [taskcluster/taskcluster-cli#81]
A previous attempt at a command line client in javascript exists (see [gregarndt/taskcluster-cli](https://github.com/gregarndt/taskcluster-cli)).

This client should be able to replace that javascript implementation. 

* `taskcluster task create` to replace `taskcluster run`: creates and schedules a task
* `taskcluster task run` to replace `taskcluster run-task`: creates, schedules, and watches a task (streaming logs from _public/logs/live.log_ by default)
* `taskcluster task await` to wait the completion of a given task (by taskId)

This depends on #23 and is related to #60.

**Comment by djmitche** [comment]
Good find!  Yes, the first two represent good functionality.

`run-graph` refers to the [task-graph scheduler](https://github.com/taskcluster/task-graph-scheduler), which is deprecated -- instead, graphs are now constructed task-by-task, with the dependencies included in the task definition.  So I don't think there's much need to reproduce that functionality.

**Comment by t0xicCode** [comment]
Sounds good. I'll remove it.
