### ISSUE TITLE
Lose the timestamp warning in Task Creator after "Update Timestamps" is clicked

### ISSUE THREAD

**Issue by lteigrob** [taskcluster/taskcluster-cli#84]
Get rid of the timestamp error that shows up in Task Creator for an out-of-date task, once the timestamps have been updated. The warning remains even though the task is valid to be re-run.

**Comment by t0xicCode** [comment]
@lteigrob is this a tc-cli issue or should it be filled with taskcluster/taskcluster-tools?

**Comment by djmitche** [comment]
I opened https://bugzilla.mozilla.org/show_bug.cgi?id=1344409 for it.  Can you fill in steps to reproduce on that bug?
