### ISSUE TITLE
Create a `taskcluster status` command

### ISSUE THREAD

**Issue by djmitche** [taskcluster/taskcluster-cli#85]
This command would call (maybe in parallel?) the `ping` endpoint for every service that has one, printing an "OK!" line for each service for which it returns successfully.

Users would find this helpful when something goes wrong and they wonder, as they always do, "is taskcluster down?"  There's also https://status.taskcluster.net that shows about the same data.

**Comment by petemoore** [comment]
@djmitche Is anyone working on this already, or would this be a good starter for @yasch007?

**Comment by t0xicCode** [comment]
Seems like this was merged some time ago, I'll close this!
