### ISSUE TITLE
`taskcluster pulse-publish` command

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-cli#88]
A command `taskcluster pulse-publish [--format yaml|json] [--message <message>] <exchange> <routingkey>`

That if no `--message` is given opens a prompt that you can enter the message into...
Also it should declare the exchange if it doesn't exist.

Read more about pulse here: https://wiki.mozilla.org/Auto-tools/Projects/Pulse

Similar to #87 we can store the username/password in the config system for taskcluster-cli... These should also default to `PULSE_USERNAME` and `PULSE_PASSWORD` env vars, if not config values are entered...
Notice: this should primarily be based on the stuff in config/...

Ideally, we can reuse the same config options so you don't have to set the password twice...
Maybe for this to work it as to be `taskcluster pulse` with two subcommands `publish` and `listen`, either way let's start by implementing one of these.

**Comment by djmitche** [comment]
Couldn't this use taskcluster-pulse to get temporary pulse credentials?

**Comment by jonasfj** [comment]
We can when `taskcluster-pulse` is deployed and configured with real pulse admin credentials...
Last I heard that wasn't the case. From what I understand there is still some details to figure out.
