### ISSUE TITLE
Round out taskclutster-github testing

### ISSUE THREAD

**Issue by lteigrob** [taskcluster/taskcluster-cli#92]
Now we have .taskcluster.yml going (see #49), we want to be able to run some of the extra things we had for travis:

- go test -v race
- go fmt -s -w
- gometalinter --disable-all --enable=gotype --enable=golint --enable=deadcode --enable=staticcheck --enable=deadcode --enable=misspell --enable=vet --enable=vetshadow --enable=gosimple --enable=varcheck --enable=aligncheck --enable=errcheck --enable=ineffassign --enable=unconvert --enable=staticcheck --enable=goimports --enable=unused
(from #25, see for more details)

**Comment by lteigrob** [comment]
Good progress on this in commit #96. A lot of issues were found and fixed (#98, #100). We also ended up ignoring the autogenerated apis/services.go (#100). 

There's a few extra enables still needed besides the main ones:
--enable=varcheck --enable=aligncheck --enable=errcheck --enable=ineffassign --enable=unconvert -enable=goimports --enable=unused
And go fmt is still missing. 

Also, @djmitche, are we okay ignoring these other files in the apis directory? 
doc.go  provider.go
and I imagine I should close this an open another issue for the rest...

**Comment by djmitche** [comment]
I'm not thrilled about it, but it seems to be a limit of gometalinter, so we'll survive.

Let's hold off adding more checkers for the moment -- I think the incremental value we get from them will be minimal right now, and we'll get a better value by adding more test code.

**Comment by lteigrob** [comment]
Sounds good, I was thinking those would be back-burner issues but didn't want to forget them either
